### ISSUE TITLE
Possible Kopernicus Bug/incompatibily with To boldy go

### ISSUE THREAD

**Issue by crazyduck33** [prestja/Kopernicus#27]
Already opened some time ago a Ticket in the other Kopernicus Github.

In KSP 1.7 with Kopernicus and To boldy go it works without issue, since KSP 1.8 it does not work anymore.
Kopernicus starts to generate the planets as it should but it will always cancel if a Planet has this set 
VertexHeightOffset﻿
{
enabled = true
order = 2
offset = -5000 //match up with other deformities
}﻿﻿ 
and show this error in logfile
"[Kopernicus]: Configuration.Loader: Failed to load Body: Amallon VI: Value cannot be null.
Parameter name: type" 
This happens for every Planet that has the VertexHeightOffset set.

If i remove this from the To boldy go Template and geenrate a new Galaxy file Kopernicus create all Planets without problems.

So not sure if its a bug or if something in Kopernicus is changed and now the To boldy go Templates need some Updates.

**Comment by R-T-B** [comment]
I will check what changed between 1.7/1.8 and see if this is an intended change (maybe they dropped support for some value of VertexHeightOffset), but more likely I suspect it's a bug.

To be perfectly clear, you did test this against the latest 1.9.1 stable build, correct?  It has some workarounds for null parameters in bodies that just may fix this as a side effect, specifically in body types, which seemingly is the issue here.

Also for that template, is that a gas giant by chance?

As mentioned elsewhere, I will be busy over this weekend, but I will report if I find any details in the interim.  Just little chance much coding/a proper fix will get done until later this week.

**Comment by crazyduck33** [comment]
Last test i did was some days ago but wil give it another try today just to be sure. 
The template itself is this file
[pqsTmp.txt](https://github.com/prestja/Kopernicus/files/4977509/pqsTmp.txt)

If the VertexHeightOffset setting is removed kopernicus works.

**Comment by StollD** [comment]
That VertexHeightOffset string contains an invisible character at the end, which means that Kopernicus can't find a PQSMod loader with that name.

You can test that yourself easily. Copy the VertexHeightOffset string from that linked txt file, or from the initial issue. Open this page: https://github.com/prestja/Kopernicus/blob/master/src/Kopernicus/Kopernicus.csproj, press Ctrl-F, and paste the text you copied. Your browser should display that no occurences were found.

Now press backspace once in the search field. You will see that the text doesn't change, but suddenly, the browser will find something.

**Comment by crazyduck33** [comment]
The invisble string happend after i copy it back to the template file. The original file is this one 
[pqsTmp.txt](https://github.com/prestja/Kopernicus/files/4977783/pqsTmp.txt)

it does not have a invisbile character at the end of the string but Kopernicus still give me the same Error Message.

**Comment by seanth** [comment]
Also interested in this for TBG update reasons. If there _were_ a cryptic invisible character being introduced, why would things have worked with older versions of Kopernicus?

**Comment by StollD** [comment]
@crazyduck33 the character exists in that file too. Put the cursor at the end of the VertexHeightOffset line and press backspace. For the first press, nothing should actually change, since the invisible character gets deleted.

If that doesnt work, try to delete the line, and retype it. That should fix the issue too (in case your editor does some magic when trying to delete it).

@seanth Because Kopernicus < 1.8 ignores PQS mods it doesn't know. Kopernicus >= 1.8 errors if you try to use one that it doesn't know.

**Comment by crazyduck33** [comment]
@StollD true thats good to know removed it and wil see now if it works again with the Value or not :)
I thought you meant something like a empty space after the last letter.

**Comment by R-T-B** [comment]
@StollD to the rescue!  Good show, those invisible chars will be the death of us.  We need to assign watch for them or something, that's at least two bugs I can attribute to things like that.

Closing as a mod issue.  Good guidance on how to fix though, good work 

I'll gladly reopen if the bug still exists after fixing.

**Comment by democat3457** [comment]
(I think you pinged the wrong person RTB lol)

**Comment by R-T-B** [comment]
> (I think you pinged the wrong person RTB lol)

lol phone typo, thanks.  Fixed.
