### ISSUE TITLE
Removing Stock asteroids break SENTINEL contracts

### ISSUE THREAD

**Issue by drake127** [prestja/Kopernicus#31]
It looks that by destroying ScenarioDiscoverableObjects SENTINEL detections cease to work (as the SENTINEL asteroids are created in ScenarioDiscoverableObjects): https://github.com/prestja/Kopernicus/blob/master/src/Kopernicus/RuntimeUtility/DiscoverableObjects.cs#L69-L82

Would it be possible to somehow disable only Kerbin and Dres related asteroids while keeping ScenarioDiscoverableObjects running for SENTINEL?

Also 1.10 comets are likely not generated by Kopernicus asteroid implementation.

**Comment by R-T-B** [comment]
"Also 1.10 comets are likely not generated by Kopernicus asteroid implementation."

I suspect they are not.  Probably should note that in my builds.

I'm not familiar with these systems, can anyone else weigh in on how best to deal with these issues?

**Comment by R-T-B** [comment]
I'm actually wondering, looking over this bug:

Is there any reason whatsoever Kopernicus is managing asteroids, at all?  Why don't we just hand them off to the stock systems, hence fixing this, and restoring comets, etc?

If you want to declare an asteroid, declare it as a planet?  I dunno.  Makes sense from my perspective.

**Comment by R-T-B** [comment]
No that won't work, we have all sorts of fun functions with asteroids stock won't enable us to do.

Ok then, I think sadly, this is a wontfix.  The best I could do is offer a simple config file option that allows ScenarioDiscoverableObjects to run, but really, I think the best way for now is just to decline those contracts, sadly.

As for comets, We are looking at introducing them with KopernicusExpansion, using existing code we have.  May even make it stock in Kopernicus since it's stock in KSP now.

Won't slap the wontfix label on you just yet, giving others time to weigh in, but I think this is pretty much the only set of options we have and I'm not fond of running the ScenarioDsicoverableObjects code just for this select situation.

**Comment by R-T-B** [comment]
Yeah, this is more than a wontfix.  We need at least to remove sentinel contracts from generation if going that route, so leaving open.

**Comment by drake127** [comment]
Comets can probably be spawned by Kopernicus implementation but I don't like disabling SENTINELs completely. I believe that currently only Kerbin and Dres asteroids are spawned implicitly. You need SENTINEL to detect (spawn) an asteroid on other planet orbits and farther from target bodies).

What sort of magic does Kopernicus do? Isn't it possible to have both implementations running beside each other? I don't know what I am missing but I enabled ScenarioDiscoverableObjects for myself and kept Kopernicus implementation running. Stock is running just fine and Kopernicus is driven by System.cfg (Kerbin & Dres) which I disabled. Isn't that enough for standard configurations?

RSS-like mods considered, they can always use their own configuration with Kopernicus implementation (in future with comets?).

**Comment by R-T-B** [comment]
> What sort of magic does Kopernicus do? Isn't it possible to have both implementations running beside each other? I don't know what I am missing but I enabled ScenarioDiscoverableObjects for myself and kept Kopernicus implementation running. Stock is running just fine and Kopernicus is driven by System.cfg (Kerbin & Dres) which I disabled. Isn't that enough for standard configurations?

Kopernicus at present allows us to customize asteroid spawning in it's entirety.

I suppose it would be possible to add a config option to enable stock asteroid generation alongside this.  The thing about running them alongside each other is largely a performance concern...  we already cap the number of asteroids running around due to it getting a bit crazy at times.  Also some packs may not WANT asteroids near kerbin, etc.  But if we add it as a configuration option, it solves both.  I think having a little "settings.cfg" for Kopernicus to allow the user to make choices like this might not be a bad idea.

For right now I've disabled the contracts, but I agree, an option to opt-in to the builtin system is more ideal and I will pursue that as the ultimate solution longterm.  It will probably be a release or so as there are bigger bugs right now, but I'll do it.

**Comment by R-T-B** [comment]
The next release will use stock asteroid subsystem enabled in a config option by default.  Planet pack authors can shut it down if they wish via a config file.  Being tested in bleeding edge now, you can grab a release if you'd like.

**Comment by drake127** [comment]
I didn't tried it but I looked at the changes. I think that by keeping stock asteroids you need to also disable Kopernicus Kerbin and Dres asteroids (https://github.com/prestja/Kopernicus/blob/master/build/GameData/Kopernicus/Config/System.cfg#L507-L551). Otherwise we'd get twice as many asteroids, right?

**Comment by R-T-B** [comment]
You might.  I need testing there.  I think the game stills caps them.

If we have to do that in the end, it could be done by editing system.cfg.  I'd eventually do it modside if it's required, but right now you could do it with a module manager patch or something.

I'm not good at module manager, so this MIGHT work.  Don't quote me on that.  Only use if getting doubled asteroids, put in a cfg file:

@Kopernicus:AFTER[Kopernicus]
{
!Asteroid{}
}

**Comment by R-T-B** [comment]
Also, closing this issue as the solution is more or less implemented, but don't feel afraid to suggest changes here still as I'll monitor it in case we need to have an option to remove Kopernicus stock asteroids or something.
