### ISSUE TITLE
Broken lighting on gas gaints

### ISSUE THREAD

**Issue by ra4nd0m** [prestja/Kopernicus#33]
Lighting broken both in science archive and in game.
![image](https://user-images.githubusercontent.com/58385866/90438560-d3428380-e0dc-11ea-886d-bc505450f03c.png)
![image](https://user-images.githubusercontent.com/58385866/90438610-e8b7ad80-e0dc-11ea-9e7a-de57fa57e6c7.png)
![image](https://user-images.githubusercontent.com/58385866/90438626-f10fe880-e0dc-11ea-961c-666b7f0f86f5.png)
Clean install Kop 191.1-RC_HF3
![image](https://user-images.githubusercontent.com/58385866/90438712-1270d480-e0dd-11ea-9596-3386d0632ff3.png)
[Player.log](https://github.com/prestja/Kopernicus/files/5086518/Player.log)

**Comment by ra4nd0m** [comment]
Maybe somehow connected to that Jool shader disabler code that caused this bug in 1.10? Or these are separate branches?

**Comment by democat3457** [comment]
iirc the normal map needs to be at 50% opacity to rotate in the correct direction (towards the local star)?

**Comment by R-T-B** [comment]
Yeah, I know what causes this.  It was my attempt to fix this bug by using builtin cloudmaps:

https://github.com/R-T-B/Kopernicus/issues/18

The builtin cloudmaps seem bugged though.  So either we use a desaturated, pale normal map and get correct shadows, or we don't and we get this.

Any ideas?  I'll consult an artist friend of mine to see if he can make our included generic normal map not desaturate so bad.  If so, the fix is easy and simple and not a show stopper.

**Comment by R-T-B** [comment]
I fixed it, release pending.  We just had to use a generic flat normal map (can be made easily as I just did), not the thing we had before that I grabbed randomly from some example and just assumed worked.

The apperance may differ slightly from former releases but it is more than acceptable, and lighting works.

**Comment by R-T-B** [comment]
Got this bug fixed in hotfix 4.  Due to the simplicity of the fix, I do not consider this a blocker to CKAN.
