### ISSUE TITLE
Ground Scatter spawning at incorrect altitudes

### ISSUE THREAD

**Issue by Poodmund** [prestja/Kopernicus#5]
I recently noticed that ground scatter was spawing in above/below the ground when it was being loaded at a far away distance. Here's a really easy and quick reproduction test:

- Start new Sandbox game
- Create a vessel with a capsule, tank and engine and launch
- Cheat vesel into a vessel in low-orbit on one side of Minmus. I did as lower altitude as possible with a Longitude of Ascending Node of 180 degrees to spawn into dark side of Minmus
- Time warp around to the opposite, lit side of Minmus
- Kill velocity and descend to the surface
- You'll see that a lot of the ground scatter is hovering above the surface.

I've noticed that this issue seems to have been introduced during the 5 commits to the main trunk Kopernicus repo on the 7th/8th March as the ground scatter seems to behave normally using a compiled build from the 4th March commits: https://github.com/Kopernicus/Kopernicus/commits/master. I see that these 5 commits do make changes to the ModuleScatter components so something may be tripping up here. I see these changes have also been incorporated into this new fork.

Weirdly, if you encounter this issue you can resolve it by quick-saving and then quick-loading, however, if you then take off from the surface again and travel to the opposite side of the body (somewhere very far away) you then re-encounter the issue on this far away point again.

I think it seems to be spawning ground scatter in too early/too distant away from the camera so its spawning on quads that are of a lower detail level than sufficient causing them to spawn above and below ground.

Here is a video of me doing this on the latest KSP 1.9.1 build and Kopernicus 1.9.1.1-Pre: https://www.youtube.com/watch?v=Jn4-DJo8nRI

Corresponding log files of the above video session can be found here: https://www.dropbox.com/s/ndaw69atztvzkhx/Logs.zip?dl=0

**Comment by StollD** [comment]
The issue lies in this commit: https://github.com/Kopernicus/Kopernicus/commit/e5883b23e44db433bd4421db178ec757276834e2

The ModularScatter code uses two loops inside Update: One for creating new scatter objects, and one for removing those that are no longer assigned. 

What Sigma did was to move the code for removing theese objects from the "remove loop" into the "creation loop". In theory that could work fine, but how it was done caused a conflict: When a scatter gets unassigned, it is no longer active, and it's GameObject gets disabled. But in the "creation loop" you only care about objects which have been assigned and are active already (because Kopernicus wants to take over their mesh generation).

If you only look at the commit you don't see the issue, which confused me a bit initially. But if you open the full file you can see what happens: https://github.com/Kopernicus/Kopernicus/blob/e5883b23e44db433bd4421db178ec757276834e2/src/Kopernicus/Components/ModularScatter/ModularScatter.cs#L227-L230

The loop will check if the object is active, and if not, skip it (because it is not relevant for creating new ones). This means that the code that should remove unassigned objects won't run anymore, and objects from lower subdivision levels will stick around.

The solution for that would be to simply revert the commits https://github.com/Kopernicus/Kopernicus/commit/e5883b23e44db433bd4421db178ec757276834e2, https://github.com/Kopernicus/Kopernicus/commit/e5d52cb512b71c6355e9f886699fe97dc77fd372 and https://github.com/Kopernicus/Kopernicus/commit/486ca8b846065af946129f02ddf9b445cb33fd4b. Even if they would work, there would be no FPS difference.

**Comment by R-T-B** [comment]
I remember those commits.  They were in the name of improving scattering performance.  Sounds like they did a whole lot of nothing good really.

I'll try removing them on my branch soon.  If all goes well with that, I will suggest a PR from my branch to merge.

**Comment by Sigma88** [comment]
Those changes probably were bundled together with changes for other systems (modular scatter iirc) that were causing a lot of fps loss, so it's possible that the difference in FPS was noticeable thanks to the other changes and those were just pointless.
if reverting the commits does not increase FPS than it should be a pretty easy fix

**Comment by R-T-B** [comment]
I have tested the reverts and indeed, they work with minimal performance loss.  Please see my Pull Request:

https://github.com/prestja/Kopernicus/pull/7

**Comment by R-T-B** [comment]
This has to my knowledge, been fixed a few releases ago, so closing.
